# Generated by Django 2.2.3 on 2020-07-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('passwd', models.CharField(max_length=40)),
                ('mobileno', models.CharField(default='', max_length=50)),
                ('qualification', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=50)),
                ('status', models.CharField(default='', max_length=40)),
            ],
            options={
                'db_table': 'userregister',
            },
        ),
    ]
