# Generated by Django 2.2.3 on 2020-07-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_uploadmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='status',
            field=models.CharField(default='waiting', max_length=600),
        ),
    ]
