# Generated by Django 2.2.3 on 2020-07-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_uploadmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
